name: chat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.4.0
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.6
  device_preview: ^1.2.0
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  firebase_storage: ^12.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.19.0
  photo_view: ^0.15.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.3.2
  uuid: ^4.4.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/n_logo.svg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
